import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString } from "class-validator";

export class TwoFactorResponseDto {
  @ApiProperty({
    description: "Base64 image of the QR code to scan in your authenticator app",
    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
  })
  qrCode: string;

  @ApiProperty({
    description: "Base32-encoded TOTP secret key",
    example: "JBSWY3DPEHPK3PXP",
  })
  secret: string;

  @ApiProperty({
    description: "Same as the secret, used for manual entry into 2FA apps if QR scanning is not available",
    example: "JBSWY3DPEHPK3PXP",
  })
  manualEntryKey: string;
}

export class EnableTwoFactorResponseDto {
  @ApiProperty({
    description: "Indicates if two-factor authentication has been enabled for the user",
    example: true,
  })
  enabled: boolean;

  @ApiProperty({
    description: "Success message indicating that two-factor authentication has been enabled",
    example: "Successfully enabled two-factor authentication",
  })
  secret: string;

  @ApiProperty({
    description: "Backup codes that can be used to log in if the user loses access to their authenticator app",
    example: ["code1", "code2", "code3", "code4", "code5"],
    type: [String],
  })
  backupCodes: string[];
}

export class EnableTwoFactorDto {
  @ApiProperty({
    description: "Base32-encoded TOTP secret key",
    example: "JBSWY3DPEHPK3PXP",
  })
  @IsString()
  @IsNotEmpty()
  secret: string;

  @ApiProperty({
    description: "OTP code generated by the authenticator app",
    example: "000000",
  })
  @IsString()
  @IsNotEmpty()
  code: string;
}

export class ErrorResponseDto {
  @ApiProperty({
    description: "Error message describing the issue",
    example: "An Error Occured/Unauthorized/Bad Request",
  })
  @IsString()
  message: string;

  @ApiProperty({
    description: "HTTP status code of the error",
    example: 400,
  })
  @IsString()
  statusCode: number;
}
